# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'AzLinux DCR Public (8e037ad4-618f-4466-8bc8-5099d41ac15b)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      set -euxo pipefail
      xargs --version
      date=`date --utc +%Y-%m-%d'T'%H:%M'Z' -d "1 day ago"`
      az rest --method GET --url "https://management.azure.com/subscriptions/8e037ad4-618f-4466-8bc8-5099d41ac15b/resourcegroups" --url-parameters api-version=2021-04-01 \$expand=createdTime --output json --query value | jq --arg date "$date" '.[] | select (.createdTime < $date).name' | grep "dcr-v2-test" | xargs -ol
      #   -r az group delete --no-wait -y -n
